In [1]:
#import dependencies
import pandas as pd
import numpy as np

In [6]:
#save path to dataset to the variable 'best_seller_data'
best_seller_data = "Resources/Amazon_Best_Seller_2021_June.csv"

#read in the csv with pandas and display the header of the file
best_seller_df = pd.read_csv(best_seller_data)
best_seller_df.head(10)

,ASIN,Category,Product Link,No of Sellers,Rank,Rating,Reviews Count,Price
0,B079QHML21,Electronics,https://www.amazon.com/gp/offer-listing/B079QH...,1 Sellers,#1,4.7,"640,721",$39.99
1,B07FZ8S74R,Electronics,https://www.amazon.com/gp/offer-listing/B07FZ8...,1 Sellers,#2,4.7,"854,114",$34.99
2,B07XJ8C8F5,Electronics,https://www.amazon.com/gp/offer-listing/B07XJ8...,1 Sellers,#3,4.7,"267,821",$44.99
3,B07WVFCVJN,Electronics,https://www.amazon.com/gp/offer-listing/B07WVF...,27 Sellers,#4,4.8,"114,267",$28.48
4,B08YT2N5SX,Electronics,https://www.amazon.com/gp/offer-listing/B08YT2...,1 Sellers,#5,4.7,"267,821",$49.99
5,B07TMJ1R3X,Electronics,https://www.amazon.com/gp/offer-listing/B07TMJ...,1 Sellers,#6,4.6,"100,278",$89.99
6,B07X6C9RMF,Electronics,https://www.amazon.com/gp/offer-listing/B07X6C...,1 Sellers,#7,4.5,"111,650",$34.99
7,B08BX7FV5L,Electronics,https://www.amazon.com/gp/offer-listing/B08BX7...,1 Sellers,#8,4.5,"1,228",$149.99
8,B075XLWML4,Electronics,https://www.amazon.com/gp/offer-listing/B075XL...,67 Sellers,#9,4.7,"85,934",$39.00
9,B089DR29T6,Electronics,https://www.amazon.com/gp/offer-listing/B089DR...,1 Sellers,#10,4.7,"434,174",$24.99

In [15]:
#clean the dataframe so that 'No of Sellers' Column only shows numerical values instead of string values
best_seller_df['No of Sellers'] = best_seller_df['No of Sellers'].str.replace(r"[a-zA-Z]",'')

#clean the datafram so that the Rank Column only shows numerical values-- remove pound signs
best_seller_df['Rank'] = best_seller_df['Rank'].str.replace(r"[#]", '')

#create a new dataframe without the product link and ASIN column
reduced_best_seller_df = best_seller_df[["Category", "No of Sellers", "Rank", "Rating", "Reviews Count", "Price"]]

#display result
reduced_best_seller_df.head(20)

       Category No of Sellers Rank  Rating Reviews Count     Price
0   Electronics            1     1     4.7       640,721   $39.99
1   Electronics            1     2     4.7       854,114   $34.99
2   Electronics            1     3     4.7       267,821   $44.99
3   Electronics           27     4     4.8       114,267   $28.48
4   Electronics            1     5     4.7       267,821   $49.99
5   Electronics            1     6     4.6       100,278   $89.99
6   Electronics            1     7     4.5       111,650   $34.99
7   Electronics            1     8     4.5         1,228  $149.99
8   Electronics           67     9     4.7        85,934   $39.00
9   Electronics            1    10     4.7       434,174   $24.99
10  Electronics            1    12     4.7        83,773  $139.99
11  Electronics            1    13     4.4        54,100  $249.99
12  Electronics            1    14     4.7       267,821   $49.99
13  Electronics            1    15     4.7       267,821   $44.99
14  Electronics            1    16     4.6       395,830   $59.99
15  Electronics            1    17     4.6       110,685  $129.99
16  Electronics            1    18     4.0       116,633   $49.99
17  Electronics           32    19     4.8        59,785   $13.22
18  Electronics            1    20     4.7       854,114   $34.99
19  Electronics            1    21     4.6        38,016  $149.99